### ISSUE TITLE
Promisifying all methods of a ES6 Class instance doesn't seem to work

### ISSUE THREAD

**Issue by filipesilva** [sindresorhus/pify#57]
The readme example shows it should be possible to promisify all methods in a module.

```
// Promisify all methods in a module
pify(fs).readFile('package.json', 'utf8').then(data => {
	console.log(JSON.parse(data).name);
	//=> 'pify'
});
```

This doesn't seem to work for ES6 class instances:

```
// test.js
const pify = require('pify');

class MyClass {
  myMethod(cb) {
    cb(null, 'hello');
  }
}

const myClass = new MyClass();
// works
myClass.myMethod((err, str) => console.log(str));
// works
pify(myClass.myMethod)().then(data => console.log(data));
// does not work
pify(myClass).myMethod().then(data => console.log(data));
```
```
$ node test.js
hello
D:\sandbox\master-project\test.js:13
pify(myClass).myMethod().then(data => console.log(data));
              ^

TypeError: pify(...).myMethod is not a function
    at Object.<anonymous> (D:\sandbox\master-project\test.js:13:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

I'm not sure if this is by design or not though. The example clearly says "Promisify all methods in a **module**", so maybe it should only be used for CommonJS modules.

**Comment by sindresorhus** [comment]
It's a limitation of ES6 Classes. Its methods are not enumerable. I'll document it.

**Comment by evilebottnawi** [comment]
@sindresorhus maybe we can add options for this?

**Comment by filipesilva** [comment]
@sindresorhus thanks for letting us know 👍

**Comment by sindresorhus** [comment]
Yeah, could be an option that used `Object.getOwnPropertyNames()` instead, but I think a better fix is for someone to finish https://github.com/sindresorhus/pify/pull/32 which will just transparently support this and other edge-cases.

**Comment by sallar** [comment]
This is how I fixed this for now:

```js
  // Get method names
  const methods = Object.getOwnPropertyNames(
    Object.getPrototypeOf(__client)
  ).filter(name => name !== 'constructor');

  // Promisify all methods
  methods.forEach(method => {
    __client[method] = pify(__client[method]);
  });
```
